### ISSUE TITLE
Alumni should see "my requests" and "decisions" but shouldn't make new dataset requests 

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_AlumniManagement#18]
is this with core feature management possible?

**Comment by EleonoraPetzold** [comment]
Create Request and "my requests" and "decisions" are in the same controller and rights on this function are not Handleable separately.

@aostrow @CFuerstenau how do we deal with it?

**Comment by EleonoraPetzold** [comment]
will be done as a core issue: https://github.com/BEXIS2/Core/issues/872
If it is available then we will set the alumni feature.

**Comment by geofranzi** [comment]
wie vergebt ihr die Rechte für die Alumni gruppe? Direkt oder über ein Gruppe?
 das müsste jetzt noch für Alumni gesetzt werden.

**Comment by EleonoraPetzold** [comment]
Ich hab das Requests Manage feature der alumni gruppe hinzugefügt. Danke Franzi :)
